name: Update PR branch

on:
  workflow_dispatch:
    inputs:
      locale-id:
        description: Locale ID
        type: string
        default: it
        required: true
      base-branch:
        description: Upstream base branch
        type: string
        default: main
        required: false
      pr-branch:
        description: Pull request branch
        type: string
        required: false
        # @todo remove following line once https://github.com/bluesky-social/social-app/pull/6775 gets merged
        default: update-it

jobs:
  update-pr-branch:
    name: Update PR branch
    runs-on: ubuntu-latest
    steps:
      -
        name: Parse inputs
        id: parse-inputs
        env:
          LOCALE_ID: ${{ inputs.locale-id }}
          BASE_BRANCH: ${{ inputs.base-branch }}
          PR_BRANCH: ${{ inputs.pr-branch }}
        run: |
          if ! grep -qE '^[a-z]{2}(-[A-Z]{2,3})?$' <<< "$LOCALE_ID"; then
            echo 'Invalid locale ID'
            exit 1
          fi
          if [ -z "$BASE_BRANCH" ]; then
            BASE_BRANCH=main
          fi
          if [ -z "$PR_BRANCH" ]; then
            PR_BRANCH=update-$BASE_BRANCH-$LOCALE_ID
          fi
          echo "locale-id=$LOCALE_ID" >>"$GITHUB_OUTPUT"
          echo "base-branch=$BASE_BRANCH" >>"$GITHUB_OUTPUT"
          echo "pr-branch=$PR_BRANCH" >>"$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      -
        name: Checkout ${{ steps.parse-inputs.outputs.pr-branch }} branch
        id: checkout-pr-branch
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.parse-inputs.outputs.pr-branch }}
      -
        name: Checkout default branch
        if: steps.checkout-pr-branch.outcome == 'failure'
        uses: actions/checkout@v4
      -
        name: Add upstream repository
        if: steps.checkout-pr-branch.outcome == 'failure'
        run: git remote add upstream https://github.com/bluesky-social/social-app.git
      -
        name: Fetch ${{ steps.parse-inputs.outputs.base-branch }} branch of upstream repository
        if: steps.checkout-pr-branch.outcome == 'failure'
        run: git fetch upstream '${{ steps.parse-inputs.outputs.base-branch }}'
      -
        name: Create ${{ steps.parse-inputs.outputs.pr-branch }} branch based on ${{ steps.parse-inputs.outputs.base-branch }}
        if: steps.checkout-pr-branch.outcome == 'failure'
        run: git checkout -b '${{ steps.parse-inputs.outputs.pr-branch }}' 'upstream/${{ steps.parse-inputs.outputs.base-branch }}'
      -
        name: Fetch new .po file
        id: fetch-po
        run: |
          MY_TARGET_PO='src/locale/locales/${{ steps.parse-inputs.outputs.locale-id }}/messages.po'
          if [ ! -f "$MY_TARGET_PO" ]; then
            echo '${{ steps.parse-inputs.outputs.locale-id }} is not a currently supported locale'
            cd src/locale/locales
            echo 'Valid locales are:'
            find * -maxdepth 0 -type d
            exit 1
          fi
          MY_SOURCE_PO='https://github.com/mlocati/bluesky-social-app/raw/refs/heads/transifex-bridge/po/${{ steps.parse-inputs.outputs.base-branch }}/${{ steps.parse-inputs.outputs.locale-id }}.po'
          curl -sSLf -o "$MY_TARGET_PO" "$MY_SOURCE_PO"
          if git diff --color=always --exit-code "$MY_TARGET_PO"; then
            echo 'No changes'
          else
            echo 'commit=yes' >>"$GITHUB_OUTPUT"
          fi
      -
        name: Commit
        if: steps.fetch-po.outputs.commit == 'yes'
        run: |
          git add src/locale/locales
          git config user.name GitHub
          git config user.email noreply@github.com
          git commit -m 'Update po from Transifex'
          git push
