name: Update POT files

on:
  schedule:
    - cron: 0 0,12 * * *
  workflow_dispatch:
    
jobs:
  update-pot-files:
    name: Branch ${{ matrix.bs-branch }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        bs-branch:
          - main
    steps:
      -
        name: Checkout Bluesky repository
        uses: actions/checkout@v4
        with:
          repository: bluesky-social/social-app
          ref: ${{ matrix.bs-branch }}
      -
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      -
        name: Install dependencies for Bluesky repository
        run: yarn install --frozen-lockfile
      -
        name: Generate .pot file
        run: ./node_modules/.bin/lingui extract-template
      -
        name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: pots-repo
      -
        name: Install dependencies for this repository
        working-directory: pots-repo
        run: npm ci
      -
        name: Check differences
        id: update-pot
        working-directory: pots-repo
        run: node index update-pot "${{ matrix.bs-branch }}" ../src/locale/locales/messages.pot pot "$GITHUB_OUTPUT"
      -
        name: Commit
        id: commit
        if: steps.update-pot.outputs.updated == 'yes'
        working-directory: pots-repo
        run: |
          git add pot
          git config user.name GitHub
          git config user.email noreply@github.com
          git commit -m 'Update pot for branch ${{ matrix.bs-branch }}'
          echo "sha1=$(git rev-parse HEAD)" >>"$GITHUB_OUTPUT"
          git push
      -
        name: Notify update
        if: steps.update-pot.outputs.updated == 'yes'
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TG_BOT_TOKEN }}
          to: ${{ secrets.TG_CHAT_ID }}
          disable_web_page_preview: true
          message: |
            Action https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} updated the .pot files for Transifex.
            See commit https://github.com/${{ github.repository }}/commit/${{ steps.commit.outputs.sha1 }}
      -
        name: Notify failures
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TG_BOT_TOKEN }}
          to: ${{ secrets.TG_CHAT_ID }}
          disable_web_page_preview: true
          message: Updating POT files failed on https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
